### ISSUE TITLE
How should we share 3D models?

### ISSUE THREAD

**Issue by KoalaGeo** [GeoEra-GIP/Project-Support-WP8#1]
?

**Comment by nmtoken** [comment]
What do we mean by 3D models?

**Comment by KoalaGeo** [comment]
Or 2.5D?

**Comment by nmtoken** [comment]
2.5-D is a 2-D dataset draped onto a 3-D surface; the data doesn't suddenly become 3-D in such a situation, but it gives the appearance of 3-D, hence 2.5-D

A globe itself may also not be regarded as 3-D if the surface does not have 3 dimensions (x,y,z), it's just another 2-D representation.  So a 2-D dataset draped on a 2-D globe is 2-D not even 2.5-D

**Comment by nmtoken** [comment]
We might also want to distinguish between sharing (exchanging/downloading) models and accessing models.  

So you could for example have some index/catalogue that shows you where models exist and what they do... then give a download ~ so no web view of the model itself, and no direction interaction with it.  

and/or you could have some service that interacts with the model, so for example creates a synthetic cross section (for web view or not) or ask some numerical question~ you never get to see the whole model.

and/or you might want some 3D or pseudo-3D view of the model...

For accessing the model we might envisage WCS/WCPS/WPS services

For viewing an index and download WMS/CSW both would work.

**Comment by nmtoken** [comment]
So consider the following.

We have a 3-D voxel model on a server and we query it to make a set of 2-D slices along each axis (x-y-z), then we fetch them all and show them in a browser

We are accessing the 3-D model and making a pseudo-3D representation that we can interact with. 

![3d-visualization1](https://user-images.githubusercontent.com/1692891/51338051-b8cba280-1a80-11e9-8113-5881f3e0e28d.png)

![3d-visualization2](https://user-images.githubusercontent.com/1692891/51338062-bd905680-1a80-11e9-9165-3cec538dde12.png)

![3d-visualization3](https://user-images.githubusercontent.com/1692891/51338068-c1bc7400-1a80-11e9-841a-a6bb810b66eb.png)

**Comment by nmtoken** [comment]
Similarly we can have multiple 3D geological surfaces, and query them to make a queryable model in a browser like:

![3d surfaces](https://user-images.githubusercontent.com/1692891/51338837-c8e48180-1a82-11e9-8f18-3b5b2b855a39.png)
