### ISSUE TITLE
Link to TerraFirma on GeoHazards page is incorrect

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#194]
Link to TerraFirma on GeoHazards page (http://www.europe-geology.eu/geohazards/) is incorrect (no longer resolves.

Link is given as _http://www.terrafirma.eu.com/_

**Comment by nmtoken** [comment]
goes to https://eu.com/

**Comment by bgsmase** [comment]
@JorgenTulstrup can you get in touch with whoever maintains the EGDI website to update this link?

**Comment by bgsmase** [comment]
@JorgenTulstrup confirms he can change the website but doesn't have an up to date link for the project. I found https://www.eurogeosurveys.org/projects/terrafirma/ also points to the above no longer functioning link so I will email eurogeosurveys to find out what has happened.

**Comment by bgsmase** [comment]
EuroGeoSurveys have been contacted. The original project websites (for Terrafirma and also for PanGeo) are no longer maintained but we have some contact names for people who may know whether the data that was there is available anywhere else or can be made so. @nmtoken will follow up.

**Comment by nmtoken** [comment]
Could use? https://www.bgs.ac.uk/research/earthHazards/epom/Terrafirma.html for project information

and data products could link to BGS simple feature WFS services.

**Comment by bgsmase** [comment]
@JorgenTulstrup do you think James' suggested replacement links above would do instead of the current broken ones?

**Comment by JorgenTulstrup** [comment]
On the page that James suggests there is a link further on to http://www.terrafirma.eu.com/. I think this should be the one we link to from EGDI.
Regarding the links to the data products I will need to speak with Bjarni about that but I don't know if he attends this conversation. How can I check that?
And then one more thing: Do you have any information about PanGeo?

**Comment by nmtoken** [comment]
@JorgenTulstrup  http://www.terrafirma.eu.com/ is the link that wasn't working in the first place, so now it is back all is well.  It was going to a web domain available page, so somebody probably forgot to renew the domain name.  I see the listed Pangeo page now goes to a French fanzine.  I assume somebody forgot to renew the domain name and in the time it was available somebody else has registered it.   

Bjarni is not a listed member https://github.com/orgs/GeoEra-GIP/people we can invite him, or you could deal with him directly.

**Comment by nmtoken** [comment]
done as much as we can to point out issue and have some resolution
