### ISSUE TITLE
There is no contact email for support in the EGDI portal

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#195]
There is no contact email for support in the EGDI portal, or any other way to request assistance or report an issue.

http://www.europe-geology.eu/map-viewer/

**Comment by KoalaGeo** [comment]
Ping @JorgenTulstrup

**Comment by nmtoken** [comment]
http://www.europe-geology.eu/

**Comment by bgsmase** [comment]
Ping @JorgenTulstrup

**Comment by bgsmase** [comment]
Ping @JorgenTulstrup

**Comment by nmtoken** [comment]
EGDI don't yet have any agreed support
