### ISSUE TITLE
Check SGU minerals service for INSPIRE compliance

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#207]
Service URL is: https://resource.sgu.se/service/wms/inspire/MR-Mineralresurser?

**Comment by nmtoken** [comment]
[1] WMS GetCapabilities is schema valid

[2] MetadataURL points to invalid resource 

> https://www.geodata.se/geodataportalen/srv/en/csw-inspire?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&id=fdc2a96a-530b-4d51-8158-a81dc520438d&outputSchema=csw:IsoRecord

[3] Minerals Commodity legend(s) looks correct 

... WIP

**Comment by tomlind** [comment]
Thanks for checking!
I suspect our national metadata catalog is having some problems. I did not get a response using the URL above early this morning but it seems to be working now without any action from me. Could you please try again?

**Comment by nmtoken** [comment]
Working for me now (I get a record) but previously I got a response but no record.

**Comment by auretepereira** [comment]
Are you using the INSPIRE validator for validate the service? http://inspire.ec.europa.eu/validator/

**Comment by nmtoken** [comment]
@auretepereira not yet

**Comment by nmtoken** [comment]
So for the WMS 1.3 test only the INSPIRE validator fails the service, we should note that this might reflect issues in the validator (which is in beta) rather than the WMS.

One issue is a test was expecting an exception response, when a request is sent without a mandatory parameter (request=GetCapabilities);  though possibly this is a little harsh because the response is actually the GetCapabilities response.

I think I understand how this has occurred ~ there's a static file at the GetCapabilities endpoint, so whatever parameters are given you always get a response, and the service itself is perfectly functional.

**Comment by nmtoken** [comment]
Another issue is reported as:

    A BoundingBox is provided for non existing CRS either in the layer itself nor in a parent layer.

but as far as I can see, that's incorrect, there are 20 reported CRS and 20 BBOX (for the same CRS)

**Comment by nmtoken** [comment]
Next failure is:

    A layer's Identifier has a non unique value for its authority.

Where the authority is:

    <Identifier authority="SGU">

Well I agree it's possible that SGU as an authority might be a duplication across INSPIRE authorities, I'm not sure if that's what's being tested here

**Comment by nmtoken** [comment]
There's a failure against layer name (even though I only requested a WMS 1.3 test, not INSPIRE themes).

    The following layers do not have a correct name according with the harmonised layer names given in the INSPIRE collection: 'MR.SGU.MineralResources, MR.Commodity, MR.CommodityIndustrialMinerals, MR.CommodityBuildingMaterials, MR.CommodityCeramic, MR.CommodityChemicalUse, MR.CommodityPreciousGemstones, MR.CommodityPreciousMetals, MR.CommodityEnergy, MR.CommodityRareMetals, MR.CommodityIronMetals, MR.CommodityBaseMetals, MR.ProcessingPlant, MR.MiningWaste, MR.MiningActivity, MR.MineralOccurence'.

Let's unpick this...

**Layers to be provided by INSPIRE view services**

> MR.Mine

and

> MR.MineralOccurrence

So MR.MineralOccurence in the SGU service is incorrect because of spelling (Occurrence not Occurence).  

Also the legislation says the title must be `Mineral Occurrences` so `MineralfÃ¶rekomster (MineralOccurence)` is also incorrect here.

There is a MR.Mine layer.

That fulfils the obligations, though if you don't have mines data or had mines data but not occurrences information, it would be interesting how you could provide an INSPIRE service ...

So  `MR.SGU.MineralResources` is the root layer name and not invalid.

Now the fun bit.

Table 6 in the data specification _Listed Layers for MR Commodity_  (so that's a layer that's not required, or even mentioned)

- MR.CommodityBaseMetals
- MR.CommodityIronMetals
- MR.CommodityRareMetals
- MR.CommodityEnergy
...

So those are the same layer names that are rejected by the WMS 1.3 validator

and having a group layer MR.Commodity as a container for these seems perfectly allowable (as discussed in the INSPIRE thematic cluster forum).

**Comment by nmtoken** [comment]
A genuine error found by the validator is:

> https://maps3.sgu.se/geoserver/inspire/ows?BBOX=11.2075310914546%2C55.3671957158819%2C24.1035511519344%2C68.9681779468207&CRS=CRS%3A84&FORMAT=image%2Fpng&HEIGHT=500&LAYERS=MR.SGU.MineralResources&REQUEST=GetMap&SERVICE=WMS&STYLES=&VERSION=1.3.0&WIDTH=500

gives an error (a request for the root layer should give a map response, even if you wouldn't normally do it).

The layer `inspire:MR.SGU.MineralResources` or even just `MR.SGU.MineralResources` doesn't exist in the service (as opposed the static capabilities file).

**Comment by nmtoken** [comment]
Next reported issue, is interesting  (a test of the optional transparent parameter)

> https://maps3.sgu.se/geoserver/inspire/ows?BBOX=11.2075310914546%2C55.3671957158819%2C24.1035511519344%2C68.9681779468207&CRS=CRS%3A84&FORMAT=image%2Fpng&HEIGHT=500&LAYERS=MR.SGU.MineralResources&REQUEST=GetMap&SERVICE=WMS&STYLES=&TRANSPARENT=true&VERSION=1.3.0&WIDTH=500

So same layer as above was used to test, and fails because of this, but funnily enough a strictly the test should fail, because an invalid parameter value is sent (values are case sensitive and the allowed values for transparent are **(TRUE|FALSE)** but the test request uses **true**

**Comment by tomlind** [comment]
Thanks a lot. We will investigate and hopefully solve these issues. I know we have issues on the WFS also, maybe we should add a check issue for that also.

**Comment by nmtoken** [comment]
Not important for validation, but if you add the `<Keyword>Erml_lite_queryable_geoserver</Keyword>`  keyword to your layers,  the service will be able to resymbolized in the OneGeology Portal.  Currently, the analysis tool allows reportrayal using queries on commodity and on mineral occurrence type (or both).

**Comment by tomlind** [comment]
Finally we have started to do some more systematic validation using the ETF Validator. Some of the things you point out are common to all of our services, since we are using Geoserver with static capabilities in front, and your comments have been very helpful, thanks again!

Some issues we can fix rather easy, and on others we have some comments or questions. I will comment them one by by one in comments below

**Comment by tomlind** [comment]
> A genuine error found by the validator is:
> 
> > https://maps3.sgu.se/geoserver/inspire/ows?BBOX=11.2075310914546%2C55.3671957158819%2C24.1035511519344%2C68.9681779468207&CRS=CRS%3A84&FORMAT=image%2Fpng&HEIGHT=500&LAYERS=MR.SGU.MineralResources&REQUEST=GetMap&SERVICE=WMS&STYLES=&VERSION=1.3.0&WIDTH=500
> 
> gives an error (a request for the root layer should give a map response, even if you wouldn't normally do it).
> 
> The layer `inspire:MR.SGU.MineralResources` or even just `MR.SGU.MineralResources` doesn't exist in the service (as opposed the static capabilities file).

This has always been confusing to me. What is the root layer supposed to give as a map response? Actually I have never really understood the need for the root layer, and in our new version of Geoserver there is an option to don't add a root layer in the publishing tab. We have not tested that option yet.

@nmtoken How are BGS others handling this problem, or are you avoiding it somehow?

I guess we have the same problem with our group layers in the MR and GE services, they are not giving map responses. It can't see that the ETF validator reports this, is that not a problem or has the root layer some specific meaning?

**Comment by nmtoken** [comment]
Well perhaps I was being a little harsh to say you might never use the root layer, it is after all another group layer, and sometimes group layers are useful.  You could have it so all your sub layers are available at different scales, or have point layers to always show on top of polygons, but when you have multiple layers of the same type and at the same scale (as say in a geology and minerals service) it is less useful.

BGS OneGeology services (own and hosted) are mainly MapServer which renders the root layer.  BGS also use ArcGIS (which doesn't support it) and GeoServer...

I do occasionally use static GetCapabilities files to test and 'proxy' services (usually to change metadata) etc, but I it might be that services should be properly proxied, for example using MapProxy (I haven't yet tested but others are ~ https://github.com/OneGeology/TechnicalDiscussion/issues/8)  or perhaps just cascaded through another WMS to ensure a valid response.

On your other group layers not showing an ETF error, I think it's because it's not tested, rather than anything else.  On group layers in GeoServer (and indeed MapServer) there are several different types, and choosing one over another may affect your outcome, for GeoServer I think you need 'Named Tree Mode'

**Comment by nmtoken** [comment]
Closing as mostly resolved now.  New services can be re-checked under a new issue
