### ISSUE TITLE
CGI codelist GeologicRelationType

### ISSUE THREAD

**Issue by schmar00** [GeoEra-GIP/Project-Support-WP8#264]
is the CGI codelist GeologicRelationType still in draft mode or can it be used as a standard in a GeoERA project officially? An example for that would be http://resource.geosciml.org/classifier/cgi/geologicfeaturerelation/faulted_against which currently doesn't dissolve.

**Comment by nmtoken** [comment]
It's moved from draft to review, but not yet released.

**Comment by nmtoken** [comment]
I've bounced an email to the steward for the codelist, to confirm status and likely timeline to making live.

**Comment by nmtoken** [comment]
Had an out of office (till 29th June) response from the steward, so hope will have some response soon.

**Comment by nmtoken** [comment]
Will ping steward again for comment

**Comment by nmtoken** [comment]
pinged again on 17/9

**Comment by bgsmase** [comment]
No response from vocabulary steward so will have to assume this is not going to be officially published any time soon. Closing issue.
