### ISSUE TITLE
Support for coverage data

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#282]
We have an issue raised by TACTIC concerning adding  grid data into GeoPackage.  Input data is ESRI ASCII grid.  I see in the http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/main-content/DeliveringDataToEGDI document that both .asc and .grd is supported for Delivering 3D models, would it be correct to say those formats also work for for 2D coverages?

It has been mentioned but not referenced that GeoTIFF and NetCDF will also be supported, is that correct?

For grid data supplied as a GeoPackage raster will EGDI support the Tiled Gridded Coverage Data extension?

**Comment by nmtoken** [comment]
@mh-geus-dk  

Are you able to confirm ASCII grid is an allowable format for any coverage data, for example the example in issue https://github.com/GeoEra-GIP/Project-Support-WP8/issues/278 from the TACTIC project

**Comment by mh-geus-dk** [comment]
As I understood the discussion the project has grids with multiple values for each cell. For this kind of data the NetCDF i sthe prefered format.
The documentation here http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/ has been updated in the last days and now also contain sections about NetCDF and GeoTIFF.

**Comment by nmtoken** [comment]
Not sure of the rationale behind the choice of GeoPackage for the TACTIC data, but can you confirm either whether GeoPackage raster (GeoPackage is mentioned but not sure if that is just the more common vector variant) or ASCII (.asc) are supported, even if not optimal.

**Comment by nmtoken** [comment]
Just capturing here, that for NetCDF, the following formats are supported for upload.

- NetCDF Classic format (CDF-1) 

- NetCDF 64-bit Offset Format (CDF-2)

- NetCDF 64-bit Data Format (CDF-5)

- NetCDF-4 Format / HDF5

**Comment by KoalaGeo** [comment]
@mh-geus-dk can you please confirm if ASCII grids are supported?

**Comment by mh-geus-dk** [comment]
The ASCII grid are supported for data going to be loaded into the 3D database. If the data should be shown as a layer on a map they should be delivered as NetCDF (if you have the same grid layout for several grids with different values) or as GeoTIFF (or geocoded JPEG 2000 if you don't mind loosing the fine details) if it only a single grid with one value.
/Martin
