### ISSUE TITLE
Create WCS based from gridded data in NetCDF format for HOVER WP5

### ISSUE THREAD

**Issue by bgsmase** [GeoEra-GIP/Project-Support-WP8#298]
HOVER WP5 are producing NetCDF files with values for "Nitrate stored in the unsaturated zone". They are considering setting up a WCS to publish this data. Information and download link at https://www.bgs.ac.uk/services/ngdc/citedData/catalogue/800dd09b-5848-4803-a70c-cd15d5590f16.html.

EGDI metadata catalogue contains record at https://egdi.geology.cz/record/basic/71ba9d69-0596-1f70-e054-002128a47908.

**Comment by bgsmase** [comment]
@nmtoken can get output from gdalinfo, but can't connect to the NetCDF file as a datasource. Has tried two different software packages.  Mapserver first then GeoServer.    GeoServer gives a warning that ' No CF-Standard File found'. Not yet investigated whether file can be converted into a CF version.

**Comment by nmtoken** [comment]
As a first step will need CF convention metadata.  Under investigation.

**Comment by bgsmase** [comment]
Conversion to CF conformant NetCDF still under investigation

**Comment by nmtoken** [comment]
We now have the data in NetCDF-CF and will try to configure a WCS to supply it

**Comment by nmtoken** [comment]
Couldn't get GeoServer (Windows) or MapServer on Windows to recognise the file.  

Preconfectioned Rasdaman (open source) doesn't come with netCDF support built in, so must compile your own version , tried guided build (on Ubuntu) but failed on `building 'netCDF4._netCDF4' extension`

MapServer on Linux can read the file, but doesn't serve it out again as the original NetCDF (serves each band as a sub-dataset), possibly be an issue with the OUTPUTFORMAT config that could be  fixed.
