### ISSUE TITLE
[FRAME WP8] GeoPackage of the REE metallogenic map of Europe delivery - feedback from GIP-P is needed

### ISSUE THREAD

**Issue by auretepereira** [GeoEra-GIP/Project-Support-WP8#311]
@mh-geus-dk 

When do you foreseen the public release of this map in EGDI?

I have some PDF files and DOI associated to this map. How do I upload this kind of documents?

Regards
@auretepereira

**Comment by nmtoken** [comment]
PDF files and DOI are up-loadable through the development EGDI admin interface, not sure when/whether this is available through a live system yet.

https://user-images.githubusercontent.com/1692891/90134635-5d9b8800-dd69-11ea-8f32-3961e7ae329e.png

**Comment by bgsmase** [comment]
@mh-geus-dk Can you answer the question about public release of the map. James has answered about the upload of PDF files.

**Comment by auretepereira** [comment]
@mh-geus-dk 
Any feedback from test data set from FRAME?

**Comment by bgsmase** [comment]
@auretepereira Is your comment on test data set from FRAME related to the original question? Is there anything that still needs answering for this issue?

**Comment by auretepereira** [comment]
Hi Marcus,
As I understand I will upload the files to EGDI myself to test them. Thank you.
