### ISSUE TITLE
Geographic location on metadata

### ISSUE THREAD

**Issue by auretepereira** [GeoEra-GIP/Project-Support-WP8#391]
@Kramolisova 
Could you please provide the longitude and latitude for datasets with spatial extent in Europe (including Greenland)? Of course I can put the values but if you provide them than all should use the same values.

Thank you in advance.
Best regards

**Comment by nmtoken** [comment]
EPSG:3034 which is the default display projection of the portal (see https://github.com/GeoEra-GIP/Project-Support-WP8/issues/346) has a bounding box of `BBOX[24.60,-35.58,84.17,44.83]`, however that doesn't cover Greenland.  

Extents for Greenland (EPSG:1107) are 

    <gmd:EX_GeographicBoundingBox>
        <gmd:westBoundLongitude>
          <gco:Decimal>-75</gco:Decimal>
        </gmd:westBoundLongitude>
        <gmd:eastBoundLongitude>
          <gco:Decimal>8.12</gco:Decimal>
        </gmd:eastBoundLongitude>
        <gmd:southBoundLatitude>
          <gco:Decimal>56.38</gco:Decimal>
        </gmd:southBoundLatitude>
        <gmd:northBoundLatitude>
          <gco:Decimal>87.03</gco:Decimal>
        </gmd:northBoundLatitude>
    </gmd:EX_GeographicBoundingBox>

Which would give a Europe bounding box of:

    <gmd:EX_GeographicBoundingBox>
        <gmd:westBoundLongitude>
          <gco:Decimal>-75</gco:Decimal>
        </gmd:westBoundLongitude>
        <gmd:eastBoundLongitude>
          <gco:Decimal>44.83</gco:Decimal>
        </gmd:eastBoundLongitude>
        <gmd:southBoundLatitude>
          <gco:Decimal>24.6</gco:Decimal>
        </gmd:southBoundLatitude>
        <gmd:northBoundLatitude>
          <gco:Decimal>87.03</gco:Decimal>
        </gmd:northBoundLatitude>
    </gmd:EX_GeographicBoundingBox>


I'm not sure though of the merit of having a metadata bounding box for a set of data (a hint to the location) that is much different to the actual extent.

**Comment by auretepereira** [comment]
In the prototype map for FRAME in EGDI you can see well Greenland. Here is the link https://data.geus.dk/egdi/?mapname=egdi_geoera_frame#baslay=baseMapGEUS&extent=-11549890,-3443450,19362370,10587820&layers=frame_metallogenic_areas,frame_mineralisation_points
That's why I'm not sure if I understand your last sentence...

**Comment by nmtoken** [comment]
What I meant was you should use the extent of the actual data in the metadata.

In the prototype map for FRAME in EGDI.  The two layers have auto-generated ISO metadata (created by MapServer)

REE mineral occurrences (prototype) has 
https://egdi.geology.cz/record/xml/5efb2a53-29d0-458a-9eee-0bfa0a010833

with

    <gmd:EX_GeographicBoundingBox>
        <gmd:westBoundLongitude>
            <gco:Decimal>-60.00</gco:Decimal>
        </gmd:westBoundLongitude>
        <gmd:eastBoundLongitude>
            <gco:Decimal>35</gco:Decimal>
        </gmd:eastBoundLongitude>
        <gmd:southBoundLatitude>
            <gco:Decimal>27.5</gco:Decimal>
        </gmd:southBoundLatitude>
        <gmd:northBoundLatitude>
            <gco:Decimal>83.50</gco:Decimal>
        </gmd:northBoundLatitude>
    </gmd:EX_GeographicBoundingBox>

and

REE metallogenic map of Europe (prototype) has
https://egdi.geology.cz/record/xml/5ef9b687-7464-48d1-a170-548a0a010833

with

    <gmd:EX_GeographicBoundingBox>
        <gmd:westBoundLongitude>
            <gco:Decimal>-60.00</gco:Decimal>
        </gmd:westBoundLongitude>
        <gmd:eastBoundLongitude>
            <gco:Decimal>35</gco:Decimal>
        </gmd:eastBoundLongitude>
        <gmd:southBoundLatitude>
            <gco:Decimal>27.5</gco:Decimal>
        </gmd:southBoundLatitude>
        <gmd:northBoundLatitude>
            <gco:Decimal>83.50</gco:Decimal>
        </gmd:northBoundLatitude>
    </gmd:EX_GeographicBoundingBox>

So I would suggest using that extent

**Comment by auretepereira** [comment]
Ok. Thanks.

**Comment by Kramolisova** [comment]
But I agree that we should correctly extend the default bounding box of Europe in the EGDI metadata catalogue to include Greenland. We will add it to the development.

**Comment by nmtoken** [comment]
@Kramolisova can  this now be closed?

**Comment by Kramolisova** [comment]
We decided within metadata team to not extend predefined spatial extent of Europe in MIcKA with Greenland yet.
