### ISSUE TITLE
[HARVESTING] How providers can check if miningfeatureoccurence <XOR> constrain is satisfied

### ISSUE THREAD

**Issue by AV-si** [GeoEra-GIP/Project-Support-WP8#429]
You need to check if one miningfeatureoccurence.miningfeatureoccurencedbk  (MFO) is linked to miningfeatureoccurencedbk  field in one and only one of mine, miningactivity, miningwaste, prosumminingactivity, prosumminingwaste, processingtransformationplant, processingtransformationactivity tables. 

To do that you can use the query below. Query return rows with  incorrectly linked MFO’s in first column. Other columns are dbk's of the tables in which MFO's are linked to. To satisfy <XOR> constrain one and only one not null dbk from connected tables is allowed. This mean that correct entries will have six [null] values in each row (but correct entries are not shown by the query).

SELECT 
t1.miningfeatureoccurrencedbk, 
t1.minedbk, 
t1.miningactivitydbk, 
t1.miningwastedbk, 
t1.processingtransformationplantdbk, 
t1.processingtransformationactivitydbk, 
t1.prosumminingactivitydbk, 
t1.prosumminingwastedbk FROM
(SELECT *, ((CASE WHEN t.minedbk IS NULL THEN 1 ELSE 0 END)
+ (CASE WHEN t.miningactivitydbk IS NULL THEN 1 ELSE 0 END)
+ (CASE WHEN t.miningwastedbk IS NULL THEN 1 ELSE 0 END)
+ (CASE WHEN t.processingtransformationplantdbk IS NULL THEN 1 ELSE 0 END)
+ (CASE WHEN t.processingtransformationactivitydbk IS NULL THEN 1 ELSE 0 END)
+ (CASE WHEN t.prosumminingactivitydbk IS NULL THEN 1 ELSE 0 END)
+ (CASE WHEN t.prosumminingwastedbk IS NULL THEN 1 ELSE 0 END)) AS sum_of_nulls FROM
(SELECT 
public.MiningFeatureOccurrence.miningFeatureOccurrenceDbk,
public.Mine.mineDbk,
public.MiningActivity.miningActivityDbk,
public.MiningWaste.miningWasteDbk,
public.ProcessingTransformationPlant.ProcessingTransformationPlantDbk,
public.ProcessingTransformationActivity.processingTransformationActivityDbk,
public.ProSUMMiningActivity.prosumMiningActivityDbk,
public.ProSUMMiningWaste.prosumMiningWasteDbk
FROM   
public.MiningFeatureOccurrence 
LEFT OUTER JOIN
public.ProcessingTransformationPlant ON public.MiningFeatureOccurrence.miningFeatureOccurrenceDbk = public.ProcessingTransformationPlant.miningFeatureOccurrenceDbk
LEFT OUTER JOIN
public.Mine ON public.MiningFeatureOccurrence.miningFeatureOccurrenceDbk = public.Mine.miningFeatureOccurrenceDbk
LEFT OUTER JOIN
public.ProcessingTransformationActivity ON public.MiningFeatureOccurrence.miningFeatureOccurrenceDbk = public.ProcessingTransformationActivity.miningFeatureOccurrenceDbk
LEFT OUTER JOIN
public.ProSUMMiningWaste ON public.MiningFeatureOccurrence.miningFeatureOccurrenceDbk = public.ProSUMMiningWaste.miningFeatureOccurrenceDbk
LEFT OUTER JOIN
public.MiningWaste ON public.MiningFeatureOccurrence.miningFeatureOccurrenceDbk = public.MiningWaste.miningFeatureOccurrenceDbk
LEFT OUTER JOIN
public.ProSUMMiningActivity ON public.MiningFeatureOccurrence.miningFeatureOccurrenceDbk = public.ProSUMMiningActivity.miningFeatureOccurrenceDbk
LEFT OUTER JOIN
public.MiningActivity ON public.MiningFeatureOccurrence.miningFeatureOccurrenceDbk = public.MiningActivity.miningFeatureOccurrenceDbk) t)t1
WHERE t1.sum_of_nulls < 6;

**Comment by nmtoken** [comment]
@AV-si do think this should be added to any documentation

**Comment by mh-geus-dk** [comment]
@AV-si That must you who can answer this.

**Comment by AV-si** [comment]
It is not necessary to publish upper code in documentation because we provide a different solution. The upper code just help providers to check <XOR> constrains in their current m4eu_v1.1.2 database. But providers will move to version m4eu_v2020.8 soon.

In new version of database (m4eu_v2020.8) the new service prosum:DBVersion will be provided for checking. This service provides a specific information in different rows in response. All the following information:
•	the providers PostgreSQL version (in response row 001), 
•	PostGIS version (in response row 002),
•	codelist version (in response row 003), 
•	m4eu database model version (in response row 004),  
•	the update status or last database modification date (in response row 005), 
•	data tables count (in response rows from 100 to 167), 
•	number of XORs with no relations (in response rows from 201 to 204), 
•	number of XOR errors with more than one relation (in response rows from 211 to 214),
will be provided remotely for each data provider by calling its prosum:DBVersion service. 

Example of prosum:DBVersion service call for GEUS test data: [https://data.geus.dk/m4eu/services/m4eu_v2020.8?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=prosum:DBVersion&sortBy=prosum:m4euVersion+A](https://data.geus.dk/m4eu/services/m4eu_v2020.8?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&TYPENAMES=prosum:DBVersion&sortBy=prosum:m4euVersion+A)

**Comment by AV-si** [comment]
The actual documentation for m4eu_v2020.8 is available at [https://geusgitlab.geus.dk/m4eu/2020-m4eu](https://geusgitlab.geus.dk/m4eu/2020-m4eu)

**Comment by nmtoken** [comment]
no further work needed
