### ISSUE TITLE
Import of GeoTIFF fails in EGDI test platform

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#435]
Trying to import a hover TIFF file with associated metadata (https://egdi.geology.cz/record/basic/600ee753-5b98-4805-af06-23100a010833)  fails as below:

    Upload failed
    Exception : ERROR: insert or update on table "map_layers" violates foreign key constraint "map_layers_fk" Detail: Key is not present in table "map_projections". org.postgresql.util.PSQLException: ERROR: insert or update on table "map_layers" violates foreign key constraint "map_layers_fk" Detail: Key is not present in table "map_projections". at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310) at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023) at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217) at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421) at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166) at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:137) at eu.egdiadmin.model.DatabaseInterface.insertTableRow(DatabaseInterface.java:306) at eu.egdiadmin.control.DatabaseController.insertLayer(DatabaseController.java:327) at eu.egdiadmin.dataimport.common.DataImporterBase.insertLayerRow(DataImporterBase.java:91) at eu.egdiadmin.dataimport.geotiff.GeoTiffDataImporter.importAsLayer(GeoTiffDataImporter.java:47) at org.apache.jsp.geopack3_jsp._jspService(geopack3_jsp.java:685) at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748)

**Comment by mh-geus-dk** [comment]
It looks like the GeoTIFF has a wrong projection. If you can share the GeoTIFF. We can be more specific.
/Martin

**Comment by nmtoken** [comment]
gdalinfo -proj4 NTT.tif 

gives:

    Driver: GTiff/GeoTIFF
    Files: NTT.tif
           NTT.tif.ovr
           NTT.tif.aux.xml
    Size is 21419, 26712
    Coordinate System is:
    BOUNDCRS[
        SOURCECRS[
            PROJCRS["unnamed",
                BASEGEOGCRS["Bessel 1841",
                    DATUM["unknown",
                        ELLIPSOID["bessel",6377397.155,299.1528128,
                            LENGTHUNIT["metre",1,
                                ID["EPSG",9001]]]],
                    PRIMEM["Greenwich",0,
                        ANGLEUNIT["degree",0.0174532925199433,
                            ID["EPSG",9122]]]],
                CONVERSION["Transverse Mercator",
                    METHOD["Transverse Mercator",
                        ID["EPSG",9807]],
                    PARAMETER["Latitude of natural origin",0,
                        ANGLEUNIT["degree",0.0174532925199433],
                        ID["EPSG",8801]],
                    PARAMETER["Longitude of natural origin",15,
                        ANGLEUNIT["degree",0.0174532925199433],
                        ID["EPSG",8802]],
                    PARAMETER["Scale factor at natural origin",0.9999,
                        SCALEUNIT["unity",1],
                        ID["EPSG",8805]],
                    PARAMETER["False easting",500000,
                        LENGTHUNIT["metre",1],
                        ID["EPSG",8806]],
                    PARAMETER["False northing",-5000000,
                        LENGTHUNIT["metre",1],
                        ID["EPSG",8807]]],
                CS[Cartesian,2],
                    AXIS["easting",east,
                        ORDER[1],
                        LENGTHUNIT["metre",1,
                            ID["EPSG",9001]]],
                    AXIS["northing",north,
                        ORDER[2],
                        LENGTHUNIT["metre",1,
                            ID["EPSG",9001]]]]],
        TARGETCRS[
            GEOGCRS["WGS 84",
                DATUM["World Geodetic System 1984",
                    ELLIPSOID["WGS 84",6378137,298.257223563,
                        LENGTHUNIT["metre",1]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433]],
                CS[ellipsoidal,2],
                    AXIS["geodetic latitude (Lat)",north,
                        ORDER[1],
                        ANGLEUNIT["degree",0.0174532925199433]],
                    AXIS["geodetic longitude (Lon)",east,
                        ORDER[2],
                        ANGLEUNIT["degree",0.0174532925199433]],
                USAGE[
                    SCOPE["unknown"],
                    AREA["World"],
                    BBOX[-90,-180,90,180]],
                ID["EPSG",4326]]],
        ABRIDGEDTRANSFORMATION["Transformation to WGS84",
            METHOD["Position Vector transformation (geog2D domain)",
                ID["EPSG",9606]],
            PARAMETER["X-axis translation",0,
                ID["EPSG",8605]],
            PARAMETER["Y-axis translation",0,
                ID["EPSG",8606]],
            PARAMETER["Z-axis translation",0,
                ID["EPSG",8607]],
            PARAMETER["X-axis rotation",0,
                ID["EPSG",8608]],
            PARAMETER["Y-axis rotation",0,
                ID["EPSG",8609]],
            PARAMETER["Z-axis rotation",0,
                ID["EPSG",8610]],
            PARAMETER["Scale difference",1,
                ID["EPSG",8611]]]]
    Data axis to CRS axis mapping: 1,2
    PROJ.4 string is:
    '+proj=tmerc +lat_0=0 +lon_0=15 +k=0.9999 +x_0=500000 +y_0=-5000000 +ellps=bessel +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'
    Origin = (-1397805.064718934008852,2142797.890088851097971)
    Pixel Size = (100.000000000000000,-100.000000000000000)
    Metadata:
      AREA_OR_POINT=Area
    Image Structure Metadata:
      COMPRESSION=LZW
      INTERLEAVE=BAND
    Corner Coordinates:
    Upper Left  (-1397805.065, 2142797.890) ( 19d52'32.95"W, 59d42'18.54"N)
    Lower Left  (-1397805.065, -528402.110) (  6d35'59.58"W, 38d19'59.72"N)
    Upper Right (  744094.935, 2142797.890) ( 20d 2'59.64"E, 64d18'40.85"N)
    Lower Right (  744094.935, -528402.110) ( 17d52'25.21"E, 40d21' 4.40"N)
    Center      ( -326855.065,  807197.890) (  2d59'34.45"E, 51d47'19.62"N)
    Band 1 Block=21419x1 Type=Float32, ColorInterp=Gray
      Min=-971.788 Max=13382.710
      Minimum=-971.788, Maximum=13382.710, Mean=nan, StdDev=nan
      NoData Value=-3.39999999999999996e+38
      Overviews: 10710x13356, 5355x6678, 2678x3339, 1339x1670, 670x835, 335x418, 168x209
      Metadata:
        STATISTICS_COVARIANCES=471.4880883239434
        STATISTICS_MAXIMUM=13382.709960938
        STATISTICS_MEAN=1.#QNAN
        STATISTICS_MINIMUM=-971.78759765625
        STATISTICS_SKIPFACTORX=1
        STATISTICS_SKIPFACTORY=1
        STATISTICS_STDDEV=1.#QNAN

**Comment by nmtoken** [comment]
Can't attach the file here as Zip as it's too big

**Comment by nmtoken** [comment]
Is the loader importer referencing the metadata when working out the projection, or is the importer relying just on the information in the TIFF?

**Comment by mh-geus-dk** [comment]
Can't you share the GeoTIFF using wetransfer or similar?

**Comment by nmtoken** [comment]
transfer to follow

**Comment by nmtoken** [comment]
https://bgs.sharefile.eu/d-s8eb5566108cd48229b828acb6f663b54

**Comment by nmtoken** [comment]
Harvesting locally (by GEUS) results in an error:

> "Exception:` The following projections (epsgs) are not supported: 9001"

EPSG:9001 is not an identifier for a spatial reference system, but rather the identifier for a lengthunit (m).  So there is some issue with the harvester reading the metadata in the GeoTIFF for it's spatial reference system, which means it can't be loaded into the EGDI PostGIS back-end.

The specific issue is unresolved, but closing the issue, because the science project has now supplied a revised dataset and the issues surrounding  loading the referenced dataset into the test system have been superseded.

**Comment by nmtoken** [comment]
For underlying issue and work around see https://github.com/GeoEra-GIP/Project-Support-WP8/issues/456
