### ISSUE TITLE
Raster in GeoPackage - Converts to RGB

### ISSUE THREAD

**Issue by KoalaGeo** [GeoEra-GIP/Project-Support-WP8#448]
Dear Hans,
We are in the final stages of the hotlime and we are preparing our datasets to be sent ( Temperature at top of reservoir, thickness of the reservoir, Heat in place for the entire reservoir and the fault network).

For the fault network, the file is a shapefile and for the others they are rasters.
We have projected them in the coordinate system that it was indicated in the instructions (see document attached) "Coordinate system for all spatial products should be ETRS89 / LCC Europe (EPSG:3034) – as confirmed by GIP-P".
When we want to add the raster to the geopackage, there is a problem as the raster gets converted....

See images below that illustrate the problem.
•	Pink raster with the right color scheme is the temperature of reservoir. As you can see is a GRID.
•	When we add it into the geopackage using the "add raster to GeoPackage" it converts it into a RGB raster (see images below).

Is it possible that we get a link to the instructions? 
In the same document there was a link on how to create the GeoPackage https://geoera-gip.github.io/documentation/data.html#providing-gis-data but this link does not work anymore.

Kind regards,
Beatriz

**Comment by KoalaGeo** [comment]
Dear Edd,

For the Geoera project Hotlime a colleague from GSI was trying to convert rasters to GeoPackage (see below – for some reason it converts unwantedly to RGB). We were looking for an instructions document supposedly at https://geoera-gip.github.io/documentation/data.html#providing-gis-data but not apparently no longer there.

My colleague Rob van Ede suggested that you know more about it? Hope you can shed some light.

Best regards,

Hans

**Comment by KoalaGeo** [comment]
Hi Hans, 

Those docs were deprecated as we felt everything should live under the EGDI or MickA docs directly. 

In the EGDI docs theres - http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/main-content/GeoPackageExamples

But this is more on vector data. 

The GDAL docs https://gdal.org/drivers/raster/gpkg.html 

“Various kind of input datasets can be converted to GeoPackage raster :
•	Single band grey level
•	Single band with R,G,B or R,G,B,A color table
•	Two bands: first band with grey level, second band with alpha channel
•	Three bands: Red, Green, Blue
•	Four band: Red, Green, Blue, Alpha
GeoPackage rasters only support Byte data type.”
If that fits with your data in QGIS you should just be able to right click > “Export Data” and choose GeoPackage as the output format. 

Cheers, 

Edd

**Comment by KoalaGeo** [comment]
Upload of GeoTIFF should be possible (try to use a generic CRS like 4326) so I’d recommend trying that first.

**Comment by mh-geus-dk** [comment]
Hi all,
If you are delivering raster data to EGDI you should deliver them as GeoTIFF if the dataset contains a single value like dept to aquifer. If your raster dataset contains several values like an annual value for a parameter you should deliver the data on the NetCDF format - see:
http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/main-content/SpatialData?id=gridded-data
The data should be delivered in  EPSG:3034 - see:
http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/main-content/SpatialData?id=projections
