### ISSUE TITLE
Uploading GeoTIFF in dev platform results in error

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#456]
Attempting to upload a GeoTIFF file supplied by the HOVER project in the development EGDI platform results in error:

    Exception: The following projections (epsgs) are not supported: 9001

    Detailed log
    java.lang.Exception: The following projections (epsgs) are not supported: 9001 at org.apache.jsp.geopack2_jsp._jspService(geopack2_jsp.java:669) at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476) at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386) at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748)

**Comment by nmtoken** [comment]
[hoverNTT.zip](https://github.com/GeoEra-GIP/Project-Support-WP8/files/6131583/hoverNTT.zip)

**Comment by mh-geus-dk** [comment]
I'm not sure why it dosn't work but both QGIS and the Adm. module gets confused by this GeoTIFF. I have tried to open it in QGIS and telling QGIS it is in EPSG:3034 and the save. After that all works smoothly. I have asked one of our GIS specialist if he tell why the original doesn't work as expected.
You can see the layer here:
https://egditest01.geus.dk/egdi/?mapname=gip_p_preview#baslay=baseMapGEUS&extent=-109460,1293070,6887510,4419370&layers=nttmh

**Comment by nmtoken** [comment]
As the same issue has occurred with two independent TIFFs could the review also focus on the expectations of the upload tool.

**Comment by mh-geus-dk** [comment]
We are and have currently received nearly 90 GeoTIFF's from HOVER, GARAH and MUSE through the Administration module.

**Comment by nmtoken** [comment]
On live and dev, or just on live?

**Comment by mh-geus-dk** [comment]
Most of them on production but also some on test.

**Comment by nmtoken** [comment]
Does this GeoTIFF work on live?

**Comment by nmtoken** [comment]
Leave you to debug the issues, and report

**Comment by mh-geus-dk** [comment]
I have added a description on how to overcome this problem in the FAQ in the EGDI User Guide:
http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/other/faq?id=i-have-problems-with-upload-of-geotiff-files

**Comment by nmtoken** [comment]
> GeoTIFF does not include a strictly defined format for the projection and in some cases the administration module cannot decifer the projection.

So the  underlying issue is that module can't parse the coordinate system information in  the WKT (_gdalinfo name-of-geotiff_ gives response in OGC WKT, by default WKT2) but relies instead on the WKT response including only a  **PROJCRS**  block which includes an **ID** with a known EPSG identifier.
