### ISSUE TITLE
Multiscaling: Restrict view below European level

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#525]
In the the Deliverable 2.1.2 report ~ https://geoera.eu/wp-content/uploads/2020/10/D2.1.2-Data-Delivery-Plan.pdf 

Under the _Functionality to be tested_ column we have in places the phrase **Multiscaling: Restrict view below European level** 

Is this something that needs to be configured for the dataset for example by setting a scale denominator in the MapServer configuration?

I can't see any mention in the documentation (http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/main-content/AdministrationModule), but I may have missed it

**Comment by mh-geus-dk** [comment]
Multiscaling can be defined in the Mapsever configuration. we haven't had any questoins about that and the user guide is driven by the questions we receive. In the near future Hike will try to upload a GeoPackagde with multiscale defined in the SLD, we are not quite sure this rather advanced SLD thematisation will work as this support is rather new in Mapserver.

**Comment by nmtoken** [comment]
So now you have received a question the documentation will be updated, that's great to hear.

**Comment by nmtoken** [comment]
I have added 

    MINSCALEDENOM 25000
    MAXSCALEDENOM 25000000

To the HOVER layer and can see it works in the EGDI Platform (and the corresponding WMS that drives it) .  MINSCALE is set below that of the EGDI platform will display, so is redundant for the platform, but not if the WMS is used outside of the platform.
