### ISSUE TITLE
Download data (no access control) / access control

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#526]
In the the Deliverable 2.1.2 report ~ https://geoera.eu/wp-content/uploads/2020/10/D2.1.2-Data-Delivery-Plan.pdf

Under the _Functionality to be tested_ column we have in places phrases like **Download data (no access control)** and **Download (no access control)** and **Download data+access control**

How is access control configured for an uploaded dataset?

I can't see any mention in the documentation (http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/main-content/AdministrationModule), but I may have missed it

**Comment by mh-geus-dk** [comment]
There will be no download with access control so no need for testing that. I'm don't know how this ended up in the deliverable. It is not something that has been promised.

**Comment by nmtoken** [comment]
So data will either be or not be accessible to the public?

In which case shouldn't there still be a way of flagging this for a dataset

**Comment by nmtoken** [comment]
Removing the download link, suggests a different mechanism than WFS (or WCS).

Should projects also deny WCS/WFS operations in the layer metadata?

like:
    "WFS_ENABLE_REQUEST" "!*"
    "WCS_ENABLE_REQUEST" "!*"
