### ISSUE TITLE
details table in EGDI map 

### ISSUE THREAD

**Issue by lbaenar** [GeoEra-GIP/Project-Support-WP8#548]
Hello,
I am trying to upload a shapefile and/or a geopackage but I do not know how to show the details table with the information for each pilot when I click on a pilot.
I am trying to create a geopackage in arcgis (I do not use QGIS). I import a feature class and a table in the geopackage with the information I want to show but it does not show in the EGDI map.
Can somebody help me with this issue?

Thank you in advance.
Leticia

**Comment by nmtoken** [comment]
I think we had a similar issue discussed in https://github.com/GeoEra-GIP/Project-Support-WP8/issues/545. 
It should just work, if not there may be an issue with your data such as perhaps invalid geometry

**Comment by lbaenar** [comment]
In the #545 issue I had the problem that I could not upload a shapefile neither a geopackage, but it was solved by creating a new user account because there was a typo error.
Now the problem is that the detail table is not showed when I click on a pilot area. I tried it by uploading a shapefile and also a geopackage (the corrected one in the issue #545 TACTIC_Pilots_WP5_Del5-fixed.zip, attached below). I reviewed the EGDI FAQ (http://egdi-public.gitlabpages.geus.dk/egdi-documentation/#/main-content/GeoPackageExamples?id=how-to-link-articles-to-a-spatial-table-with-pilot-areas) but it was not usefull for me. I would be very grateful is someone could help me to create the geopackage or the shapefile to get this functionality. Another option is that somebody share with me a geopackage (from other WP) that works well and I can try to upload it in order to test if it also works for me.

[TACTIC_Pilots_WP5_Del5-fixed.zip](https://github.com/GeoEra-GIP/Project-Support-WP8/files/6950581/TACTIC_Pilots_WP5_Del5-fixed.zip)

**Comment by nmtoken** [comment]
Sorry, to clarify.   

You had the problem of uploading the data because of the bad user account, but in the process of determining that issue, I uploaded your data, and had the issue you are describing in this issue, that is no attribute/information showing ~ see my comment on 8th July.

**Comment by lbaenar** [comment]
Exactly. 
In that issue I also commented that the attributes table was not shown and @mh-geus-dk sent the link to the EGDI FAQ, but it is not useful for me.

**Comment by mh-geus-dk** [comment]
Hi,
I'm not sure I understand the problem correctly.
I have just uploaded the data to the test site and added to to this map:
[Test map](https://egditest01.geus.dk/egdi/?mapname=giptestmap#baslay=baseMapGEUS&extent=1760550,1731230,6116430,3752940&layers=TACTIC_Pilots_WP5_Del5-fixed) and the data shows up fine when I click on a pilot site. Is that what you want?
I noticed that the projection in the delivered data are in EPSG:4326. EGDI is optimized for EPSG:3034
Best Martin

**Comment by lbaenar** [comment]
Dear Martin,
you are right, that is the problem. 
Have you uploaded the same geopackage that I sent on 8 August? I do not know why it does not work when I upload it. I will try again and share the result.

Thank you very much,
Leticia

**Comment by mh-geus-dk** [comment]
Yes I took the GeoPackage from your three days old post.
So it is strange it doesn't work for you. When you try again please share a link to the uploaded data set (from the "Data set" menu).
Good luck Martin

**Comment by lbaenar** [comment]
Thank you very much, Martin. I have uploaded the geopackage again and I created a new web map with the projection EPSG: 3034 and now it works. I think the problem could be the web map.

I think we can close this issue.

Best regards,
Leticia
