### ISSUE TITLE
WMS for M4EU?

### ISSUE THREAD

**Issue by KoalaGeo** [GeoEra-GIP/Project-Support-WP8#56]
Dear all,

Hope to find you all well.

Here in Portugal, our current version of M4EU is 2017-Prosum-v1.1.2.

Does someone have experience implementing Inspire compliant WMS services with this version, that can be shared in this forum?

We are afraid that in order to create an Inspire compliant WMS service,
deegree webservices 3.4 should be used so that WMS 1.3.0 can be provided.
Can someone please confirm this?

Kind regards,
Manuel Filipe Santos.
LNEG

**Comment by KoalaGeo** [comment]
@ManuelFilipeSantos65 copied your query to the issues page to get more assistance.

**Comment by nmtoken** [comment]
Generally, for any INSPIRE WMS, WMS version 1.3.0 is preferred but not mandated, you will though need to add an extended capabilities section, which some older software might not support.

**Comment by nmtoken** [comment]
The M4EU is 2017-Prosum-v1.1.2 database is configured to provide complex features through a WFS, for a WMS you'll need to create some additional views to flatten the data to allow portrayal using ERML-Lite.

**Comment by nmtoken** [comment]
For the ERML-Lite symbolization, the INSPIRE technical guidelines are a bit of a mess (see http://ogcdev.bgs.ac.uk/BGS_EN_MINERALS/INSPIRE.html for an HTML version).  

I created an SLD to try and cover the requirements and posted it on the INSPIRE thematic cluster, that SLD has been added to by Tomas Lindberg of Swedish Geological Survey (https://inspire.ec.europa.eu/forum/file/view/214857/sld-for-geoserver-mineraloccurrences-primarycommodity), and that has been modified again (after discussions in the ERML working group) to give the attached

[ERML-SLD_documents.zip](https://github.com/GeoEra-GIP/Project-Support-WP8/files/3967923/ERML-SLD_documents.zip)

For deegree WMS configuration though, I'm not sure that you can use SLD to configure the symbolization.  You can use GeoServer to do this.  I have the symbolization for MapServer too which is my preferred way for configuring an INSPIRE WMS.

**Comment by bgrotan** [comment]
By the way, GEUS has updated their hosted cookbooks on M4EU and Deegree deliverables on https://geusgitlab.geus.dk/m4eu/2019-ORAMA-v2.xx/tree/master/00-cookbook-m4eu/G4.1.01%20M4EU%20Tool%20Stack%20guidelines

**Comment by bgrotan** [comment]
But no, you do not need Deegree to create an Inspire compliant WMS service. You could do it by Mapserver or any other WMS 1.3.0 capable server where you can configure extended capabilities.

**Comment by nmtoken** [comment]
@bgrotan Can you confirm it is still the case, that the M4EU database structure still needs to be flattened to serve ERML-Lite simple feature WFS and ERML-Lite attributed WMS.

**Comment by bgrotan** [comment]
Sorry, can't say to be honest.

**Comment by nmtoken** [comment]
Are there any examples of the M4EU services running supplying ERML-Lite simple feature WFS and ERML-Lite attributed WMS?

**Comment by fscgeus** [comment]
To my knowledge there is no services from M4EU running ERML-lite
Frands

**Comment by nmtoken** [comment]
Thanks @fscgeus I was trying to work out if the current published deegree M4EU database structure would allow the setting up of such a set of services. 

Is the fact that there are no such services at the moment a reflection of the fact that it is no possible, or that nobody has done it?

**Comment by tomlind** [comment]
(this was ealier posted at https://github.com/orgs/GeoEra-GIP/teams/raw-materials)

Dear all,

SGU has published a Inspire compliant WMS service for Mineral Resources based on the M4EU-database. At least we have tried our best, there are probably some issues when validating using Inspire validators:)

However, we are not using deegree at all for the WMS. We have tried conform to ERML-Lite for the view service and transform data from the M4EU-database using FME, and put ERML-Lite tables on our normal datastore for Geoserver, which is the mapserver we are using for all other services than the M4EU WFS.

URL to our service:
https://resource.sgu.se/service/wms/inspire/MR-Mineralresurser?

Please comment, there are probably a lot to discuss on symbolisation and layer structure. I am probabaly not up to date with all initiatives in EGDI/GIP-P

**Comment by nmtoken** [comment]
Hi Tomas,

So you're confirming that some additional flattening needs to occur on the existing M4EU database structure, for ERML-Lite base services.

Could you perhaps share the FME ETL (rules) you used to flatten the structure?

**Comment by tomlind** [comment]
Hi,
 I attached some undocumented but rather straightforward FME workspaces that should give you an idea of our ETL rules. They include SQL statements that I think should be referencing the m4eu database only. There are a lot of constants "unpopulated" since we didn't have data, other providers may have to include that in the mapping.

The output data are tables on our external datastore (postgis) for Geoserver that we use for all our WMS.
(Our m4eu WFS for harvesting is the normal deegree WFS provided by GEUS, we don't have a ERML Lite WFS so far).

[FME_ERML_Lite.zip](https://github.com/GeoEra-GIP/Project-Support-WP8/files/4293778/FME_ERML_Lite.zip)

**Comment by KoalaGeo** [comment]
@ManuelFilipeSantos65 did this answer your query?
