### ISSUE TITLE
Geopackage upload not working on final EGDI Admin

### ISSUE THREAD

**Issue by renatabarros** [GeoEra-GIP/Project-Support-WP8#567]
Hello all, I just tried to upload a geopackage (with point shapefile named gsi_geom & simple styling) into the preview map on the final uploading system for EGDI, and nothing appears on the map (first screenshot). The same geopackage is correctly displayed in the test server (second screenshot), uploading it exactly the same way. Any idea of what might be happening? Thank you

![image](https://user-images.githubusercontent.com/28729938/136579161-eee3053e-c7a2-4003-bd8a-38b97e4a8797.png)

![image](https://user-images.githubusercontent.com/28729938/136579212-fc500ea3-b927-479c-9943-76617ceb95e0.png)

**Comment by nmtoken** [comment]
Possibly same unresolved issue as #562

**Comment by nmtoken** [comment]
If you run the Mapserver-definition test on your data do you get a blank image or some error
