### ISSUE TITLE
Raster style is not applied

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Project-Support-WP8#572]
Applying the following style to the HOVER dataset on the production platform results in a blank image.  The style works in MapServer elsewhere.; can't see if there are any other issues with configuration because of error in Map-tester, as reported in issue #571 

        CLASSITEM "[pixel]"
        # ref: https://mapserver.org/input/raster.html
        # Quantiles
        CLASS
          # Dummy for legend title
          NAME "Nitrate travel times (m/year)"
          EXPRESSION ""
          STYLE
              # No color set gives no colour/transparent
          END
        END
        CLASS
            EXPRESSION ([pixel] < 1)
            STYLE
                COLOR "#fffecc"
            END
            TITLE "Less than 1"
        END
        CLASS
            EXPRESSION ([pixel] >= 1 AND [pixel] < 2)
            STYLE
                COLOR "#ffeda0"
            END
            TITLE "1 to < 2"
        END
        CLASS
            EXPRESSION ([pixel] >= 2 AND [pixel] < 5)
            STYLE
                COLOR "#fed976"
            END
            TITLE "2 to < 5"
        END
        CLASS
            EXPRESSION ([pixel] >= 5 AND [pixel] < 7)
            STYLE
                COLOR "#feb24c"
            END
            TITLE "5 to < 7"
        END
        CLASS
            EXPRESSION ([pixel] >= 7 AND [pixel] < 10)
            STYLE
                COLOR "#fd8d3c"
            END
            TITLE "7 to < 10"
        END
        CLASS
            EXPRESSION ([pixel] >= 10 AND [pixel] < 17)
            STYLE
                COLOR "#fc4e2a"
            END
            TITLE "10 to < 17"
        END
        CLASS
            EXPRESSION ([pixel] >= 17 AND [pixel] < 21)
            STYLE
                COLOR "#e3211c"
            END
            TITLE "17 to < 21"
        END
        CLASS
            EXPRESSION ([pixel] >= 21 AND [pixel] < 39)
            STYLE
                COLOR "#bd1a26"
            END
            TITLE "21 to < 39"
        END
        CLASS
            EXPRESSION ([pixel] >= 39)
            STYLE
                COLOR "#800f26"
            END
            TITLE "Greater than or equal to 39"
        END

Issue first reported by email to GEUS on 29/9, and have been testing intermittently ever since, but with no change.

**Comment by mh-geus-dk** [comment]
We have told them that they for some reason had made the with the data source to a comment line. I have just removed the comment and now the layer is shown.
Changed this line:
#DATA "/egdi/shared/datasets/hover/ntt_epsg_3034_20210525_133153.tif"
To this:
DATA "/egdi/shared/datasets/hover/ntt_epsg_3034_20210525_133153.tif"
[See map with layer turned on](https://data.geus.dk/egdi/?mapname=egdi_geoera_hover#baslay=baseMapGEUS&extent=1210740,1162690,6306120,4231230&layers=ntt_epsg_3034)
